### PR TITLE
Wrong truncating when a container has long words without spaces

### LINKED ISSUE #31: startPos gets equal to maxTextLength wrong way
It happens with long first words (when length is almost as long as width of container)
And outcome is that it won't truncate text - just will show it full.
Sorry, for no snippet for it - writing from phone now :)
Try please, for example, for container with fixed width and just put long word at start.
Thanks!

### PR DESCRIPTION
**Pull request by Panya**
Fixes #31. See an example.

### CODE REVIEW

**Comment by vasyanik** [comment]
@ShinyChang please approve. i'll close a few tasks on my project after that :)

**Comment by ShinyChang** [comment]
Thanks @Panya .
Please try new release @vasyanik . :smile:

**Comment by Panya** [comment]
Could you publish it to npm, please?

**Comment by ShinyChang** [comment]
@Panya published. Sorry :(

**Pull request merged**
